Bug fix - adding Students to a Class.
The error was:
MongoError: Field name duplication not allowed with modifiers

It occurred because the version field (__v) was left on User documents that should be updated, on the existing Students of the Class.
This field should not be a part of the update.